---
sdkversion: 5.4.0
name: RhoMobileApplication21
version: '1.0'
vendor: rhomobile
build: debug
applog: rholog.txt
android:
  version: 4.1.0
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
wm: ''
win32:
  deployqt: '1'
  deploymsvc: '1'
rhobundle:
  exclude_items:
  - thumb.db
app_type: rhoelements
capabilities: []

